spring:
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_batch_fetch_size: 100
        #     show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect




logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
